<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfKDtRK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfKDtRK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfKDtRK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfKDtRK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfKDtRK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfKDtRK',
    'container.build_id' => 'd205128f',
    'container.build_time' => 1600696674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfKDtRK');
